### ISSUE TITLE
Display test indicators in sticky scroll headers

### ISSUE THREAD

**Issue by macbookandrew** [chiefmyron/phpunit-test-workbench#103]
I love the pass/fail/running test indicators in the gutter.

How feasible would it be to display them in the sticky scroll header as well? Try the `editor.stickyScroll.enabled` setting:

![SCR-20240607-ljvm](https://github.com/chiefmyron/phpunit-test-workbench/assets/784333/cc011124-8cea-48ef-a2b5-830b37630da6)

**Comment by chiefmyron** [comment]
Hi @macbookandrew! Thanks for your interest in the extension.

Unfortunately, the location and behaviour of the test indicators in the editor is controlled by VS Code itself, as opposed to the framework, so there's not much I can do for this one sorry.

I like the idea though - it might be a good idea to raise the ticket in the vscode repo as a feature request.

**Comment by macbookandrew** [comment]
Thanks! Opened an issue [here](https://github.com/microsoft/vscode/issues/219135)
