### ISSUE TITLE
Highlight lines within test methods where test failures occur

### ISSUE THREAD

**Issue by chiefmyron** [chiefmyron/phpunit-test-workbench#26]
Failed assertions will give sufficient detail that the specific line causing the error can be highlighted.

In the case of failed assertions, the failure detail contains only the file path and line number:
![image](https://user-images.githubusercontent.com/7475273/196308817-9f41d871-ebfa-4e98-af90-839f47f995ae.png)

In the case of an exception, the failure detail contains an abbreviated call stack that includes line numbers:
![image](https://user-images.githubusercontent.com/7475273/196308890-2d2d678d-d39d-4658-bf2d-4dec58a519ce.png)

**Comment by macbookandrew** [comment]
@chiefmyron I just started using the extension today and looks like this feature stopped working, or isn’t working in my (Laravel) environment for some reason.

Any specific suggestions of what I could do to troubleshoot and find the problem?

**Comment by chiefmyron** [comment]
Hi @macbookandrew - thanks for giving the extension a try! This feature is now behind a setting, and is turned off by default:

![image](https://github.com/chiefmyron/phpunit-test-workbench/assets/7475273/ba59eff8-acae-4e7b-85f6-591941aa4a87)

Changing the `phpunit-test-workbench.log.displayFailuresAsErrorsInCode` setting to `true` should start to show failed assertions as highlighted errors within the code.

**Comment by macbookandrew** [comment]
Ah, thanks. It does, but apparently not for chained assertions.

I guess this is more of a feature request too: would it be possible to display the “peek” panel at the failed line too?

![SCR-20240502-sclq](https://github.com/chiefmyron/phpunit-test-workbench/assets/784333/a3787800-3145-45b7-b42b-0fa02726aee5)

Here’s how [another plugin](https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit) I’ve used shows failures: 

![SCR-20240502-sgxb](https://github.com/chiefmyron/phpunit-test-workbench/assets/784333/af975bf3-0003-4c52-a428-8bbed84c52d4)

I’ve not really worked on VS Code extensions before, but if you can point me where to start, I could take a stab at that.

**Comment by chiefmyron** [comment]
That would be a really good improvement - I've created a new ticket to implement it. The good news is it shouldn't take too much to do.
