### ISSUE TITLE
code loading issues fail silently.

### ISSUE THREAD

**Issue by FrankCoder** [chiefmyron/phpunit-test-workbench#74]
I could not figure out why the tests would not run until I tried another phpunit test explorer, which output that php could not load the required file from the location specified. I moved a file and forgot to adjust the requirement.

To be quite honest, this is really frustrating. Your runner needs to forward any problem loading and running the code to the output like [VSCode PHPUnit](https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit) does.  

If you write tests first, you really need to see any issue. If I had tried to run this in the web browser, I would have seen the error way sooner. Now I've lost a lot of time, looking in the wrong place, to figure out why it just looked like the test was not running.

![testrunresult](https://github.com/chiefmyron/phpunit-test-workbench/assets/627664/38846663-82f1-4a42-bed7-23e93c47dffa)

Overall, I prefer this extension over vscode phpunit ... except for this stupid loss of time.

**Comment by chiefmyron** [comment]
Hi @FrankCoder, thanks for raising the issue. I'm travelling at the moment, but I'll look into it as soon as I can.

One thing I will say is that the output from the extension is almost directly piped from the phpunit binary - if it didn't find an issue with the file, then it's very unlikely that the extension would either. There are some basic checks that the extension performs to identify tests, but it doesn't go to the level of verifying the existence of included files - that's better suited to a language server.

That said, if you give me some more details about the before and after of the file in question, I will see if there are other checks I can add in.

**Comment by FrankCoder** [comment]
Hi @chiefmyron, thanks for the reply. 

Yeah, sorry about the annoyed tone.  I'm switching my whole project to use autoload, which will avoid this problem entirely.

Essentially the code file I was testing had a bad require statement, failing to load a dependency. 

In phpunit-test-workbench I just get no test summary, whereas in vscode.phpunit I get a stack trace that shows the failing require statement.

At the very least, when no test summary info is available, maybe provide an indication that the code being tested may not be loading.

With best practices in place, this should never happen ... but then again, there is a lot of poorly structured projects out there as mine was ;-)

**Comment by FrankCoder** [comment]
Hi @chiefmyron, 
Sorry for the late reply, I have not been working in PHP for the last few months, so I don't know if it's still an issue. If I get a chance, I will try and reproduce the problem sometime in June.

Right now, I am deeply concentrated on a new project.

Cheers!
