### ISSUE TITLE
Shift peek for test failures to appear on the line where the test failure occurred

### ISSUE THREAD

**Issue by chiefmyron** [chiefmyron/phpunit-test-workbench#98]
I guess this is more of a feature request too: would it be possible to display the “peek” panel at the failed line too?

![SCR-20240502-sclq](https://github.com/chiefmyron/phpunit-test-workbench/assets/784333/a3787800-3145-45b7-b42b-0fa02726aee5)

Here’s how [another plugin](https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit) I’ve used shows failures: 

![SCR-20240502-sgxb](https://github.com/chiefmyron/phpunit-test-workbench/assets/784333/af975bf3-0003-4c52-a428-8bbed84c52d4)

I’ve not really worked on VS Code extensions before, but if you can point me where to start, I could take a stab at that.

_Originally posted by @macbookandrew in https://github.com/chiefmyron/phpunit-test-workbench/issues/26#issuecomment-2093140495_

**Comment by macbookandrew** [comment]
Awesome — thanks!!

I’m seeing it show up on the wrong line though, I think because it’s using the last line of the stacktrace rather than the last line of code in my actual app:

![SCR-20240506-iyhd](https://github.com/chiefmyron/phpunit-test-workbench/assets/784333/6ec21eec-bd25-4d43-9a3b-f013f3bb9b92)

**Comment by macbookandrew** [comment]
> this looks like something specific to the 10.x release of Laravel, which is why I missed it. Essentially, the Illuminate\Foundation\Testing\TestCase class is extending the runTest() method of the base PHPUnit TestCase class, and so the failure is bubbled up through that class. This method is not extended in the v11.x branch, or v9.x and earlier branches - it is specific only to v10.x.

oh, interesting…that makes sense. We’ll be upgrading this specific app soon.
